import { describe, expect, it, vi } from 'vitest'
import { createMockValleyApi } from '@valley/plugin-testkit'
import { createDrawingPreviews } from '../src/previews'

const content = (id = 'shape') => JSON.stringify({ elements: [{ id, type: 'rectangle' }], appState: {}, files: {} })
const svg = (label = 'shape') => {
  const element = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
  element.setAttribute('aria-label', label)
  return element
}
const setup = () => createMockValleyApi({ manifest: { id: 'excalidraw' }, files: { 'Board.excalidraw': content() } })

describe('shared drawing previews', () => {
  it('shares reads and exports across consumers and gives each document an independent SVG clone', async () => {
    const mock = setup()
    const read = vi.spyOn(mock.api.vault, 'readFile')
    const template = svg()
    const render = vi.fn(async () => template)
    const owner = createDrawingPreviews(mock.api, render)
    const first = owner.acquire('Board.excalidraw', false, document, () => {})
    const second = owner.acquire('Board.excalidraw', false, document, () => {})
    const [a, b] = await Promise.all([first.load(), second.load()])
    expect(read).toHaveBeenCalledTimes(1)
    expect(render).toHaveBeenCalledTimes(1)
    expect(a).not.toBe(b); expect(a).not.toBe(template)
    a!.setAttribute('changed', 'yes')
    expect(b!.hasAttribute('changed')).toBe(false)
    document.body.append(a!, b!)
    a!.remove()
    expect(b!.isConnected).toBe(true)
    const other = document.implementation.createHTMLDocument('Other')
    template.setAttribute('changed-after-export', 'yes')
    const third = owner.acquire('Board.excalidraw', false, other, () => {})
    const c = await third.load()
    expect(c!.ownerDocument).toBe(other)
    expect(c!.hasAttribute('changed-after-export')).toBe(false)
    expect(render).toHaveBeenCalledTimes(1)
    b!.remove(); first.release(); second.release(); third.release(); owner.dispose()
  })

  it('keys exports by content and theme while unrelated changes and same-content revisions reuse the result', async () => {
    const mock = setup()
    let disk = content()
    const read = vi.spyOn(mock.api.vault, 'readFile').mockImplementation(async () => disk)
    const render = vi.fn(async (_scene, dark: boolean) => svg(dark ? 'dark' : 'light'))
    const owner = createDrawingPreviews(mock.api, render)
    const changed = vi.fn()
    const light = owner.acquire('Board.excalidraw', false, document, changed)
    const dark = owner.acquire('Board.excalidraw', true, document, () => {})
    await Promise.all([light.load(), dark.load()])
    expect(read).toHaveBeenCalledTimes(1); expect(render).toHaveBeenCalledTimes(2)
    mock.emitVaultChanged({ changes: [{ relPath: 'Unrelated.md', kind: 'change' }] })
    await light.load()
    expect(read).toHaveBeenCalledTimes(1); expect(changed).not.toHaveBeenCalled()
    mock.emitVaultChanged({ changes: [{ relPath: 'Board.excalidraw', kind: 'change' }] })
    await light.load()
    expect(read).toHaveBeenCalledTimes(2); expect(render).toHaveBeenCalledTimes(2)
    disk = content('new')
    mock.emitVaultChanged({ full: true })
    await light.load()
    expect(changed).toHaveBeenCalledTimes(2); expect(render).toHaveBeenCalledTimes(3)
    light.release(); dark.release(); owner.dispose()
  })

  it('rejects stale file reads and exports without blocking a current consumer or caching retired output', async () => {
    const mock = setup()
    let resolveRead!: (value: string) => void
    const read = vi.spyOn(mock.api.vault, 'readFile').mockImplementationOnce(() => new Promise((resolve) => { resolveRead = resolve }))
    let finish!: (value: SVGSVGElement) => void
    const render = vi.fn(() => new Promise<SVGSVGElement>((resolve) => { finish = resolve }))
    const owner = createDrawingPreviews(mock.api, render)
    const first = owner.acquire('Board.excalidraw', false, document, () => {})
    const stale = first.load().catch((error: Error) => error.message)
    mock.emitVaultChanged({ full: true })
    const current = first.load()
    resolveRead(content('stale'))
    expect(await stale).toContain('no longer active')
    await vi.waitFor(() => expect(render).toHaveBeenCalledTimes(1))
    finish(svg('current'))
    expect((await current)?.getAttribute('aria-label')).toBe('current')
    expect(read).toHaveBeenCalledTimes(2)
    mock.emitVaultChanged({ full: true })
    read.mockResolvedValueOnce(content('later'))
    const retired = first.load().catch((error: Error) => error.message)
    await vi.waitFor(() => expect(render).toHaveBeenCalledTimes(2))
    first.release(); finish(svg('retired'))
    expect(await retired).toContain('no longer active')
    const replacement = owner.acquire('Board.excalidraw', false, document, () => {})
    const fresh = replacement.load()
    await vi.waitFor(() => expect(render).toHaveBeenCalledTimes(3))
    finish(svg('fresh')); await fresh
    replacement.release(); owner.dispose()
  })

  it('keeps a shared export alive when only one consumer leaves and cancels queued work at unload', async () => {
    const mock = setup()
    const completions: Array<(value: SVGSVGElement) => void> = []
    const render = vi.fn(() => new Promise<SVGSVGElement>((resolve) => completions.push(resolve)))
    const read = vi.spyOn(mock.api.vault, 'readFile').mockImplementation(async (path) => content(path))
    const owner = createDrawingPreviews(mock.api, render)
    const first = owner.acquire('Board.excalidraw', false, document, () => {})
    const second = owner.acquire('Board.excalidraw', false, document, () => {})
    const a = first.load().catch((error: Error) => error.message)
    const b = second.load()
    await vi.waitFor(() => expect(render).toHaveBeenCalledTimes(1))
    first.release(); completions.shift()!(svg());
    expect(await a).toContain('no longer active'); expect(await b).toBeInstanceOf(SVGSVGElement)
    const leases = ['A', 'B', 'C'].map((path) => owner.acquire(path, false, document, () => {}))
    const pending = leases.map((lease) => lease.load().catch((error: Error) => error.message))
    await vi.waitFor(() => expect(read).toHaveBeenCalledTimes(4))
    await vi.waitFor(() => expect(render).toHaveBeenCalledTimes(3))
    owner.dispose()
    for (const complete of completions) complete(svg())
    expect(await Promise.all(pending)).toEqual(Array(3).fill('Drawing preview is no longer active'))
    expect(render).toHaveBeenCalledTimes(3)
    expect(() => owner.acquire('Board.excalidraw', false, document, () => {})).toThrow('no longer active')
    second.release(); leases.forEach((lease) => lease.release())
  })

  it('evicts retained entries and oversized SVG output without changing render results', async () => {
    const mock = setup()
    const render = vi.fn(async () => svg())
    vi.spyOn(mock.api.vault, 'readFile').mockImplementation(async (path) => content(path))
    const owner = createDrawingPreviews(mock.api, render)
    for (let i = 0; i < 34; i++) {
      const lease = owner.acquire(`Board${i}`, false, document, () => {})
      expect(await lease.load()).toBeInstanceOf(SVGSVGElement); lease.release()
    }
    const oldest = owner.acquire('Board0', false, document, () => {})
    await oldest.load()
    expect(render).toHaveBeenCalledTimes(35)
    oldest.release(); owner.dispose()
    const huge = svg()
    huge.textContent = 'x'.repeat(9 * 1024 * 1024)
    const oversized = vi.fn(async () => huge)
    const bounded = createDrawingPreviews(mock.api, oversized)
    const lease = bounded.acquire('Board.excalidraw', false, document, () => {})
    expect((await lease.load())?.textContent?.length).toBe(huge.textContent.length)
    await lease.load()
    expect(oversized).toHaveBeenCalledTimes(2)
    lease.release(); bounded.dispose()
  })

  it('bounds concurrent file reads and drops a released queued request before doing IO', async () => {
    const mock = setup()
    const finish: Array<(value: string) => void> = []
    const read = vi.spyOn(mock.api.vault, 'readFile').mockImplementation(() => new Promise((resolve) => finish.push(resolve)))
    const render = vi.fn(async () => svg())
    const owner = createDrawingPreviews(mock.api, render)
    const leases = ['A', 'B', 'C'].map((path) => owner.acquire(path, false, document, () => {}))
    const requests = leases.map((lease) => lease.load().catch((error: Error) => error.message))
    expect(read).toHaveBeenCalledTimes(2)
    leases[2].release()
    finish.forEach((resolve) => resolve(content()))
    const results = await Promise.all(requests)
    expect(read).toHaveBeenCalledTimes(2)
    expect(results[2]).toContain('no longer active')
    leases.forEach((lease) => lease.release()); owner.dispose()
  })

  it('rejects overflow beyond 32 waiting reads and cancels every admitted request on unload', async () => {
    const mock = setup()
    const finish: Array<(value: string) => void> = []
    const read = vi.spyOn(mock.api.vault, 'readFile').mockImplementation(() => new Promise((resolve) => finish.push(resolve)))
    const render = vi.fn(async () => svg())
    const owner = createDrawingPreviews(mock.api, render)
    const leases = Array.from({ length: 35 }, (_, i) => owner.acquire(`Board${i}`, false, document, () => {}))
    const requests = leases.map((lease) => lease.load().catch((error: Error) => error.message))
    expect(await requests[34]).toBe('Drawing preview queue is full')
    expect(read).toHaveBeenCalledTimes(2)
    owner.dispose()
    finish.forEach((resolve) => resolve(content()))
    expect((await Promise.all(requests)).slice(0, 34)).toEqual(Array(34).fill('Drawing preview is no longer active'))
    expect(render).not.toHaveBeenCalled()
    leases.forEach((lease) => lease.release())
  })

  it('bounds queued export bytes and allows an oversized scene only when an export slot is available', async () => {
    const mock = setup()
    const completions: Array<(value: SVGSVGElement) => void> = []
    const render = vi.fn(() => new Promise<SVGSVGElement>((resolve) => completions.push(resolve)))
    const huge = content('large') + ' '.repeat(17 * 1024 * 1024)
    vi.spyOn(mock.api.vault, 'readFile').mockImplementation(async (path) => path === 'Large' ? huge : content(path))
    const owner = createDrawingPreviews(mock.api, render)
    const leases = ['A', 'B', 'Large'].map((path) => owner.acquire(path, false, document, () => {}))
    const running = leases.slice(0, 2).map((lease) => lease.load())
    await vi.waitFor(() => expect(render).toHaveBeenCalledTimes(2))
    await expect(leases[2].load()).rejects.toThrow('queue is full')
    completions.splice(0).forEach((complete) => complete(svg()))
    await Promise.all(running)
    const retry = leases[2].load()
    await vi.waitFor(() => expect(render).toHaveBeenCalledTimes(3))
    completions.shift()!(svg('large'))
    expect((await retry)?.getAttribute('aria-label')).toBe('large')
    leases.forEach((lease) => lease.release()); owner.dispose()
  })

  it('retries failed exports and keeps separate leases even when they share an invalidation callback', async () => {
    const mock = setup()
    const render = vi.fn(async () => svg()).mockRejectedValueOnce(new Error('Font load failed'))
    const owner = createDrawingPreviews(mock.api, render)
    const changed = vi.fn()
    const first = owner.acquire('Board.excalidraw', false, document, changed)
    const second = owner.acquire('Board.excalidraw', false, document, changed)
    await expect(first.load()).rejects.toThrow('Font load failed')
    first.release()
    expect(await second.load()).toBeInstanceOf(SVGSVGElement)
    mock.emitVaultChanged({ full: true })
    expect(changed).toHaveBeenCalledTimes(1)
    expect(render).toHaveBeenCalledTimes(2)
    second.release(); owner.dispose()
  })
})
